apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: repository
    app.kubernetes.io/part-of: repository
    app.kubernetes.io/version: tbd
  name: repository-controller
