run:
  skip-dirs:
    - vendor

  skip-files:
    - ".*\\_test.go$"

linters:
  # refer https://golangci-lint.run/usage/linters/
  disable-all: true
  enable:
    # errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases
    - errcheck
    # checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification
    - gofmt
    # Linter for Go source code that specializes in simplifying code
    - gosimple
    # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - govet
    # Detects when assignments to existing variables are not used
    - ineffassign
    # Checks for misuse of Sprintf to construct a host with port in a URL.
    - nosprintfhostport
    - staticcheck
    # Like the front-end of a Go compiler, parses and type-checks Go code
    - typecheck
    # Checks Go code for unused constants, variables, functions and types
    - unused
