apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: specialzer-operator
    app.kubernetes.io/part-of: specialzer-operator
    app.kubernetes.io/version: tbd
  name: specialzer-operator-controller-porch-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: specialzer-operator-controller-porch-role
subjects:
- kind: ServiceAccount
  name: specialzer-operator-controller
