
.PHONY: all
all: fmt test

# This includes the following targets:
#   test, unit, unit-clean,
#   gosec, lint,
#   fmt, vet,
include ../../default-go.mk

# This includes the 'help' target that prints out all targets with their descriptions organized by categories
include ../../default-help.mk
