---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nfdeploy-nephio-org-v1alpha1-nfdeploy
  failurePolicy: Fail
  name: vnfdeploy.google.com
  rules:
  - apiGroups:
    - nfdeploy.nephio.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - nfdeploys
  sideEffects: None
