// Code generated by mockery v2.53.5. DO NOT EDIT.

package git

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/nephio-project/nephio/controllers/pkg/git/types"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CreateAccessToken provides a mock function with given fields: opt
func (_m *MockClient) CreateAccessToken(opt types.CreateAccessTokenOption) (*types.AccessToken, *types.Response, error) {
	ret := _m.Called(opt)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessToken")
	}

	var r0 *types.AccessToken
	var r1 *types.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(types.CreateAccessTokenOption) (*types.AccessToken, *types.Response, error)); ok {
		return rf(opt)
	}
	if rf, ok := ret.Get(0).(func(types.CreateAccessTokenOption) *types.AccessToken); ok {
		r0 = rf(opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AccessToken)
		}
	}

	if rf, ok := ret.Get(1).(func(types.CreateAccessTokenOption) *types.Response); ok {
		r1 = rf(opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(types.CreateAccessTokenOption) error); ok {
		r2 = rf(opt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClient_CreateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccessToken'
type MockClient_CreateAccessToken_Call struct {
	*mock.Call
}

// CreateAccessToken is a helper method to define mock.On call
//   - opt types.CreateAccessTokenOption
func (_e *MockClient_Expecter) CreateAccessToken(opt interface{}) *MockClient_CreateAccessToken_Call {
	return &MockClient_CreateAccessToken_Call{Call: _e.mock.On("CreateAccessToken", opt)}
}

func (_c *MockClient_CreateAccessToken_Call) Run(run func(opt types.CreateAccessTokenOption)) *MockClient_CreateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.CreateAccessTokenOption))
	})
	return _c
}

func (_c *MockClient_CreateAccessToken_Call) Return(_a0 *types.AccessToken, _a1 *types.Response, _a2 error) *MockClient_CreateAccessToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockClient_CreateAccessToken_Call) RunAndReturn(run func(types.CreateAccessTokenOption) (*types.AccessToken, *types.Response, error)) *MockClient_CreateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRepo provides a mock function with given fields: createRepoOption
func (_m *MockClient) CreateRepo(createRepoOption types.CreateRepoOption) (*types.Repository, *types.Response, error) {
	ret := _m.Called(createRepoOption)

	if len(ret) == 0 {
		panic("no return value specified for CreateRepo")
	}

	var r0 *types.Repository
	var r1 *types.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(types.CreateRepoOption) (*types.Repository, *types.Response, error)); ok {
		return rf(createRepoOption)
	}
	if rf, ok := ret.Get(0).(func(types.CreateRepoOption) *types.Repository); ok {
		r0 = rf(createRepoOption)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(types.CreateRepoOption) *types.Response); ok {
		r1 = rf(createRepoOption)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(types.CreateRepoOption) error); ok {
		r2 = rf(createRepoOption)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClient_CreateRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRepo'
type MockClient_CreateRepo_Call struct {
	*mock.Call
}

// CreateRepo is a helper method to define mock.On call
//   - createRepoOption types.CreateRepoOption
func (_e *MockClient_Expecter) CreateRepo(createRepoOption interface{}) *MockClient_CreateRepo_Call {
	return &MockClient_CreateRepo_Call{Call: _e.mock.On("CreateRepo", createRepoOption)}
}

func (_c *MockClient_CreateRepo_Call) Run(run func(createRepoOption types.CreateRepoOption)) *MockClient_CreateRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.CreateRepoOption))
	})
	return _c
}

func (_c *MockClient_CreateRepo_Call) Return(_a0 *types.Repository, _a1 *types.Response, _a2 error) *MockClient_CreateRepo_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockClient_CreateRepo_Call) RunAndReturn(run func(types.CreateRepoOption) (*types.Repository, *types.Response, error)) *MockClient_CreateRepo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccessToken provides a mock function with given fields: value
func (_m *MockClient) DeleteAccessToken(value interface{}) (*types.Response, error) {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccessToken")
	}

	var r0 *types.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (*types.Response, error)); ok {
		return rf(value)
	}
	if rf, ok := ret.Get(0).(func(interface{}) *types.Response); ok {
		r0 = rf(value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_DeleteAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccessToken'
type MockClient_DeleteAccessToken_Call struct {
	*mock.Call
}

// DeleteAccessToken is a helper method to define mock.On call
//   - value interface{}
func (_e *MockClient_Expecter) DeleteAccessToken(value interface{}) *MockClient_DeleteAccessToken_Call {
	return &MockClient_DeleteAccessToken_Call{Call: _e.mock.On("DeleteAccessToken", value)}
}

func (_c *MockClient_DeleteAccessToken_Call) Run(run func(value interface{})) *MockClient_DeleteAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockClient_DeleteAccessToken_Call) Return(_a0 *types.Response, _a1 error) *MockClient_DeleteAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_DeleteAccessToken_Call) RunAndReturn(run func(interface{}) (*types.Response, error)) *MockClient_DeleteAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRepo provides a mock function with given fields: owner, repo
func (_m *MockClient) DeleteRepo(owner string, repo string) (*types.Response, error) {
	ret := _m.Called(owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRepo")
	}

	var r0 *types.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*types.Response, error)); ok {
		return rf(owner, repo)
	}
	if rf, ok := ret.Get(0).(func(string, string) *types.Response); ok {
		r0 = rf(owner, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(owner, repo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_DeleteRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRepo'
type MockClient_DeleteRepo_Call struct {
	*mock.Call
}

// DeleteRepo is a helper method to define mock.On call
//   - owner string
//   - repo string
func (_e *MockClient_Expecter) DeleteRepo(owner interface{}, repo interface{}) *MockClient_DeleteRepo_Call {
	return &MockClient_DeleteRepo_Call{Call: _e.mock.On("DeleteRepo", owner, repo)}
}

func (_c *MockClient_DeleteRepo_Call) Run(run func(owner string, repo string)) *MockClient_DeleteRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockClient_DeleteRepo_Call) Return(_a0 *types.Response, _a1 error) *MockClient_DeleteRepo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_DeleteRepo_Call) RunAndReturn(run func(string, string) (*types.Response, error)) *MockClient_DeleteRepo_Call {
	_c.Call.Return(run)
	return _c
}

// EditRepo provides a mock function with given fields: userName, repoCRName, editRepoOption
func (_m *MockClient) EditRepo(userName string, repoCRName string, editRepoOption types.EditRepoOption) (*types.Repository, *types.Response, error) {
	ret := _m.Called(userName, repoCRName, editRepoOption)

	if len(ret) == 0 {
		panic("no return value specified for EditRepo")
	}

	var r0 *types.Repository
	var r1 *types.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, types.EditRepoOption) (*types.Repository, *types.Response, error)); ok {
		return rf(userName, repoCRName, editRepoOption)
	}
	if rf, ok := ret.Get(0).(func(string, string, types.EditRepoOption) *types.Repository); ok {
		r0 = rf(userName, repoCRName, editRepoOption)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, types.EditRepoOption) *types.Response); ok {
		r1 = rf(userName, repoCRName, editRepoOption)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(string, string, types.EditRepoOption) error); ok {
		r2 = rf(userName, repoCRName, editRepoOption)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClient_EditRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditRepo'
type MockClient_EditRepo_Call struct {
	*mock.Call
}

// EditRepo is a helper method to define mock.On call
//   - userName string
//   - repoCRName string
//   - editRepoOption types.EditRepoOption
func (_e *MockClient_Expecter) EditRepo(userName interface{}, repoCRName interface{}, editRepoOption interface{}) *MockClient_EditRepo_Call {
	return &MockClient_EditRepo_Call{Call: _e.mock.On("EditRepo", userName, repoCRName, editRepoOption)}
}

func (_c *MockClient_EditRepo_Call) Run(run func(userName string, repoCRName string, editRepoOption types.EditRepoOption)) *MockClient_EditRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(types.EditRepoOption))
	})
	return _c
}

func (_c *MockClient_EditRepo_Call) Return(_a0 *types.Repository, _a1 *types.Response, _a2 error) *MockClient_EditRepo_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockClient_EditRepo_Call) RunAndReturn(run func(string, string, types.EditRepoOption) (*types.Repository, *types.Response, error)) *MockClient_EditRepo_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with no fields
func (_m *MockClient) Get() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockClient_Expecter) Get() *MockClient_Get_Call {
	return &MockClient_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockClient_Get_Call) Run(run func()) *MockClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Get_Call) Return(_a0 interface{}) *MockClient_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Get_Call) RunAndReturn(run func() interface{}) *MockClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetMyUserInfo provides a mock function with no fields
func (_m *MockClient) GetMyUserInfo() (*types.User, *types.Response, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMyUserInfo")
	}

	var r0 *types.User
	var r1 *types.Response
	var r2 error
	if rf, ok := ret.Get(0).(func() (*types.User, *types.Response, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *types.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.User)
		}
	}

	if rf, ok := ret.Get(1).(func() *types.Response); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Response)
		}
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClient_GetMyUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyUserInfo'
type MockClient_GetMyUserInfo_Call struct {
	*mock.Call
}

// GetMyUserInfo is a helper method to define mock.On call
func (_e *MockClient_Expecter) GetMyUserInfo() *MockClient_GetMyUserInfo_Call {
	return &MockClient_GetMyUserInfo_Call{Call: _e.mock.On("GetMyUserInfo")}
}

func (_c *MockClient_GetMyUserInfo_Call) Run(run func()) *MockClient_GetMyUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_GetMyUserInfo_Call) Return(_a0 *types.User, _a1 *types.Response, _a2 error) *MockClient_GetMyUserInfo_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockClient_GetMyUserInfo_Call) RunAndReturn(run func() (*types.User, *types.Response, error)) *MockClient_GetMyUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepo provides a mock function with given fields: userName, repoCRName
func (_m *MockClient) GetRepo(userName string, repoCRName string) (*types.Repository, *types.Response, error) {
	ret := _m.Called(userName, repoCRName)

	if len(ret) == 0 {
		panic("no return value specified for GetRepo")
	}

	var r0 *types.Repository
	var r1 *types.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (*types.Repository, *types.Response, error)); ok {
		return rf(userName, repoCRName)
	}
	if rf, ok := ret.Get(0).(func(string, string) *types.Repository); ok {
		r0 = rf(userName, repoCRName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) *types.Response); ok {
		r1 = rf(userName, repoCRName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(userName, repoCRName)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClient_GetRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepo'
type MockClient_GetRepo_Call struct {
	*mock.Call
}

// GetRepo is a helper method to define mock.On call
//   - userName string
//   - repoCRName string
func (_e *MockClient_Expecter) GetRepo(userName interface{}, repoCRName interface{}) *MockClient_GetRepo_Call {
	return &MockClient_GetRepo_Call{Call: _e.mock.On("GetRepo", userName, repoCRName)}
}

func (_c *MockClient_GetRepo_Call) Run(run func(userName string, repoCRName string)) *MockClient_GetRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetRepo_Call) Return(_a0 *types.Repository, _a1 *types.Response, _a2 error) *MockClient_GetRepo_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockClient_GetRepo_Call) RunAndReturn(run func(string, string) (*types.Repository, *types.Response, error)) *MockClient_GetRepo_Call {
	_c.Call.Return(run)
	return _c
}

// IsInitialized provides a mock function with no fields
func (_m *MockClient) IsInitialized() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInitialized")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockClient_IsInitialized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInitialized'
type MockClient_IsInitialized_Call struct {
	*mock.Call
}

// IsInitialized is a helper method to define mock.On call
func (_e *MockClient_Expecter) IsInitialized() *MockClient_IsInitialized_Call {
	return &MockClient_IsInitialized_Call{Call: _e.mock.On("IsInitialized")}
}

func (_c *MockClient_IsInitialized_Call) Run(run func()) *MockClient_IsInitialized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_IsInitialized_Call) Return(_a0 bool) *MockClient_IsInitialized_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_IsInitialized_Call) RunAndReturn(run func() bool) *MockClient_IsInitialized_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccessTokens provides a mock function with given fields: opts
func (_m *MockClient) ListAccessTokens(opts types.ListAccessTokensOptions) ([]*types.AccessToken, *types.Response, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for ListAccessTokens")
	}

	var r0 []*types.AccessToken
	var r1 *types.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(types.ListAccessTokensOptions) ([]*types.AccessToken, *types.Response, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(types.ListAccessTokensOptions) []*types.AccessToken); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.AccessToken)
		}
	}

	if rf, ok := ret.Get(1).(func(types.ListAccessTokensOptions) *types.Response); ok {
		r1 = rf(opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*types.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(types.ListAccessTokensOptions) error); ok {
		r2 = rf(opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClient_ListAccessTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccessTokens'
type MockClient_ListAccessTokens_Call struct {
	*mock.Call
}

// ListAccessTokens is a helper method to define mock.On call
//   - opts types.ListAccessTokensOptions
func (_e *MockClient_Expecter) ListAccessTokens(opts interface{}) *MockClient_ListAccessTokens_Call {
	return &MockClient_ListAccessTokens_Call{Call: _e.mock.On("ListAccessTokens", opts)}
}

func (_c *MockClient_ListAccessTokens_Call) Run(run func(opts types.ListAccessTokensOptions)) *MockClient_ListAccessTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.ListAccessTokensOptions))
	})
	return _c
}

func (_c *MockClient_ListAccessTokens_Call) Return(_a0 []*types.AccessToken, _a1 *types.Response, _a2 error) *MockClient_ListAccessTokens_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockClient_ListAccessTokens_Call) RunAndReturn(run func(types.ListAccessTokensOptions) ([]*types.AccessToken, *types.Response, error)) *MockClient_ListAccessTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockClient) Start(ctx context.Context) {
	_m.Called(ctx)
}

// MockClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockClient_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Start(ctx interface{}) *MockClient_Start_Call {
	return &MockClient_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockClient_Start_Call) Run(run func(ctx context.Context)) *MockClient_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_Start_Call) Return() *MockClient_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Start_Call) RunAndReturn(run func(context.Context)) *MockClient_Start_Call {
	_c.Run(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
