# permissions for end users to view templateinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: focom-operator
    app.kubernetes.io/managed-by: kustomize
  name: provisioning-templateinfo-viewer-role
rules:
- apiGroups:
  - provisioning.oran.org
  resources:
  - templateinfoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - provisioning.oran.org
  resources:
  - templateinfoes/status
  verbs:
  - get
