---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - focom.nephio.org
  resources:
  - focomprovisioningrequests
  - oclouds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - focom.nephio.org
  resources:
  - focomprovisioningrequests/finalizers
  - oclouds/finalizers
  verbs:
  - update
- apiGroups:
  - focom.nephio.org
  resources:
  - focomprovisioningrequests/status
  - oclouds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisionresources
  - packagerevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisions/approval
  verbs:
  - get
  - update
- apiGroups:
  - provisioning.oran.org
  resources:
  - templateinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - provisioning.oran.org
  resources:
  - templateinfoes/finalizers
  verbs:
  - update
- apiGroups:
  - provisioning.oran.org
  resources:
  - templateinfoes/status
  verbs:
  - get
  - patch
  - update
