# Copyright 2022-2023 The Nephio Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: nfdeploy.nephio.org/v1alpha1
kind: NfDeploy
metadata:
  name: nfdeploy-with-all-nfs
spec:
  plmn:
    mcc: 311
    mnc: 250
  sites:
    - id: upf-dummy
      clusterName: nephio-cluster-01
      nfType: upf
      nfTypeName: UpfTypeTest
      nfVendor: nokia
      nfVersion: test-v0.1
      connectivities:
        - neighborName: smf-dummy
    - id: smf-dummy
      clusterName: nephio-cluster-01
      nfType: smf
      nfTypeName: SmfTypeTest
      nfVendor: nokia
      nfVersion: test-v0.1
      connectivities:
        - neighborName: upf-dummy
